language: ruby

# So as to use container-based infrastructure 
sudo: false

# The first three options (rvm, env, and gemfile)
# create the build matrix.
matrix:
  include:
    - rvm: 2.1.1
      gemfile: Gemfile
      env: PREP_TARGET=prep_ccs DEPLOY_TARGET=deploy_ccs PUSH_TARGET=push_ccs 
    - rvm: 2.1.1
      gemfile: Gemfile
      env: PREP_TARGET=prep_gh  DEPLOY_TARGET=deploy_gh  PUSH_TARGET=push_gh 


# Use cache, if possible (https://docs.travis-ci.com/user/caching/)
cache: bundler

bundler_args: --retry 3

# Install Jekyll and dependencies.
install:
  - bundle config build.nokogiri --use-system-libraries
  - bundle install

# branch whitelist
# The source branch and every branch starts with "pages-" for proposed changes
branches:
  only:
    - source
    - /pages-(.*)/

# Run rakefile deploy task and a script so that travis-ci won't timeout
script: 
  - bundle exec rake site:$PREP_TARGET --quiet
  - bundle exec ./summat.sh; bundle exec rake site:$DEPLOY_TARGET --quiet
  - bundle exec rake site:$PUSH_TARGET --quiet

# Global environmental variables
env:
  global:
    secure: "ZjRJN6Igf2r1Nq5JBjMeie3SdpdAFPoVb+8LEjblLLqEIaAaqFA1uC07XmOYAxpe0eDqHW0QzzFvgPOARZRGeHbRp90UZBsyOPJpa4zU5W4d8hshf+vU7w6yDIdsFVBoZOE7XigwMZX/kuu5T1FhddOCZdXx+B5wBx5EcbUr+Ds="


# Generate your secure token with the travis gem:
# 1) get Github token from your Travis CI profile page
# 2) gem install travis
# 3) travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_MAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
